KeyError: 'username'

File "C:\Users\ADITYA\Desktop\CAR POOLING\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\ADITYA\Desktop\CAR POOLING\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ADITYA\Desktop\CAR POOLING\app.py", line 131, in <module>
    main()
File "C:\Users\ADITYA\Desktop\CAR POOLING\app.py", line 78, in main
    driver_route_selection.show()
File "C:\Users\ADITYA\Desktop\CAR POOLING\screens\driver_route_selection.py", line 41, in show
    if update_driver_route(username, new_route):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ADITYA\Desktop\CAR POOLING\logic.py", line 90, in update_driver_route
    if d["username"] == username:
       ~^^^^^^^^^^^^
